cd_utils.c: OK!
cd_utils1.c: OK!
echo.c: OK!
env.c: OK!
env_null.c: OK!
exc_cmd.c: OK!
execute.c: OK!
execute_utils.c: OK!
execute_utils1.c: OK!
execute_utils2.c: OK!
execute_utils3.c: OK!
execute_utils4.c: OK!
export.c: OK!
export_utils.c: OK!
ft_cd.c: OK!
ft_exit.c: OK!
ft_pipe.c: OK!
ft_unset.c: OK!
herdoc.c: OK!
herdoc_1.c: OK!
herdoc_2.c: OK!
Heredoc_Expansion.c: OK!
heredoc_helper_0.c: OK!
heredoc_helper_1.c: OK!
heredoc_helper_2.c: OK!
heredoc_helper_3.c: OK!
libft_utils.c: OK!
libft_utils1.c: OK!
main.c: OK!
Notice: GLOBAL_VAR_DETECTED  (line:  15, col:   1):	Global variable present in file. Make sure it is a reasonable choice.
main_utils.c: OK!
main_utils_1.c: OK!
minishell.h: OK!
pwd.c: OK!
redrction.c: OK!
utils.c: OK!
parsing/add_back_func.c: OK!
parsing/add_one_shlvl.c: OK!
parsing/add_shlvl_node.c: OK!
parsing/Ambiguous.c: OK!
parsing/Ambiguous_helper.c: OK!
parsing/expand.c: OK!
parsing/expand_helper_0.c: OK!
parsing/expand_helper_1.c: OK!
parsing/expand_helper_10.c: OK!
parsing/expand_utils.c: OK!
parsing/expand_utils_10.c: OK!
parsing/expand_utils_11.c: OK!
parsing/expand_utils_12.c: OK!
parsing/expand_utils_4.c: OK!
parsing/expand_utils_5.c: OK!
parsing/expand_utils_6.c: OK!
parsing/expand_utils_7.c: OK!
parsing/expand_utils_8.c: OK!
parsing/expand_utils_9.c: OK!
parsing/find_last_node.c: OK!
parsing/free_func.c: OK!
parsing/free_func_1.c: OK!
parsing/ft_itoa.c: OK!
parsing/ft_split.c: OK!
parsing/lexer.c: OK!
parsing/lexer_helper_0.c: OK!
parsing/lexer_helper_1.c: OK!
parsing/open_files.c: OK!
parsing/open_files_helper.c: OK!
parsing/parser.c: OK!
parsing/parser_0.c: OK!
parsing/parser_helper.c: OK!
parsing/parser_helper_2.c: OK!
parsing/parser_helper_3.c: OK!
parsing/parser_helper_4.c: OK!
parsing/parsing.h: OK!
parsing/parsing_main.c: OK!
parsing/parsing_utiles.c: OK!
parsing/parsing_utiles_3.c: OK!
parsing/parsing_utiles_4.c: OK!
parsing/parsing_utiles_5.c: OK!
parsing/parsing_utiles_6.c: OK!
parsing/struc_maker.c: OK!
parsing/syntx_check.c: OK!
parsing/syntx_check_helper_0.c: OK!
parsing/syntx_check_helper_1.c: OK!
